### PR TITLE
Show bundled extension versions in `k6 run` and `k6 version` outputs

### LINKED ISSUE #1741: Display any extensions bundled by xk6 in the pre-execution output
## Feature Description
With the introduction of xk6, it is likely that we'll start to get support questions or bug reports where users are running bespoke versions of k6. From a "k6 core" point of view, the course of action would/should likely be to ask the user to try again with an official build.

That aside, if we ever want to support any extension, or make life easier for extension developers, we need some way to tell by execution logs how to replicate their builds.

## Suggested Solution
Add a new row in the pre-execution output of k6 cli. This would only be visible when k6 detects something in the 'k6/x' namespace, and should then list extensions and their versions. Mockup below:

```
          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io
  execution: local
     script: test.js
 extensions: github.com/dgzlopes/k6-extension-notifications
             github.com/dgzlopes/k6-extension-zmq
     output: -
```

With versions displayed:
```
          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io
  execution: local
     script: test.js
 extensions: github.com/dgzlopes/k6-extension-notifications@v0.2.0
             github.com/dgzlopes/k6-extension-zmq@v0.0.0-20180725130230-947c36da315
     output: -
```

Given that we've been discussing other kinds of extensions than js extensions in the future, we might also need some way to detect those. One way of doing this would be to add a tripwire to `modules.Register` instead. Personally, I'd argue that we can leave that as a future improvement and focus on the js case for now.

### PR DESCRIPTION
**Pull request by imiric**
This is based on the work done in #2754 (thanks @HarrisChu!), and the suggested changes there.

It evolved into something slightly more elaborate, where the bulk of the changes are to unify the extension registry, so that registration and retrieval of extension information is done in a single place. See commit cf5fa6102 for details. We still need to keep the existing registration functions in `js/modules/` and `output/` to avoid breaking extensions, but internally they're both now handled in the new root `ext` package. This DRYs the handling of extensions, and simplifies adding new types of extensions. It also simplifies the retrieval of extension versions, which is why it was done on top of #2754.

Here's how it currently looks:

```bash
$ xk6 build 4df8d46169ecc3a0417fd902bdcb28800e8098f0 \
  --with github.com/vesoft-inc/k6-plugin \
  --with github.com/grafana/xk6-output-influxdb
[...]

$ ./k6 version
k6 v0.41.0 ((devel), go1.19.1, linux/amd64)
Extensions:
  github.com/grafana/xk6-output-influxdb v0.2.2, xk6-influxdb [output]
  github.com/vesoft-inc/k6-plugin v1.0.1, aggcsv [output]
  github.com/vesoft-inc/k6-plugin v1.0.1, k6/x/nebulagraph [js]

$ ./k6 run ./samples/thresholds.js

          /\      |‾‾| /‾‾/   /‾‾/
     /\  /  \     |  |/  /   /  /
    /  \/    \    |     (   /   ‾‾\
   /          \   |  |\  \ |  (‾)  |
  / __________ \  |__| \__\ \_____/ .io

  execution: local
     script: ./samples/thresholds.js
 extensions: github.com/grafana/xk6-output-influxdb v0.2.2, xk6-influxdb [output]
             github.com/vesoft-inc/k6-plugin v1.0.1, aggcsv [output]
             github.com/vesoft-inc/k6-plugin v1.0.1, k6/x/nebulagraph [js]
     output: -

  scenarios: (100.00%) 1 scenario, 1 max VUs, 10m30s max duration (incl. graceful stop):
           * default: 1 iterations for each of 1 VUs (maxDuration: 10m0s, gracefulStop: 30s)
[...]
```

Closes #1741

### CODE REVIEW

File: cmd/ui.go [hunk 1]
```diff
@@ -401,3 +408,17 @@ func yamlPrint(w io.Writer, v interface{}) error {
 	}
 	return nil
 }
+
+func getExtensionsDescription(exts []*ext.Extension, leftPad, padStart int) []string {
```
Comment (olegbespalov) [inline cmd/ui.go:412]: Maybe `formatExtensionsDescription` ?

File: ext/ext.go [hunk 2]
```diff
@@ -0,0 +1,160 @@
...
+		s = "out"
+	}
+	return s
+}
+
+// Extension is a generic container for any k6 extension.
+type Extension struct {
+	Name, Path, Version string
+	Type                ExtensionType
+	Mod                 interface{}
```
Comment (olegbespalov) [inline ext/ext.go:45]: Let's name it `Module` It's not longer than `Version` and doesn't harm but helps.

File: ext/ext.go [hunk 3]
```diff
@@ -0,0 +1,160 @@
...
+		}
+		return result[i].Path < result[j].Path
+	})
+
+	return result
+}
+
+// getModuleInfo attempts to return the package path and version of the Go
+// module that created the given value.
+func getModuleInfo(mod interface{}) (path, version string) {
```
Comment (olegbespalov) [inline ext/ext.go:125]: Maybe `extractModuleInfo` ?

File: ext/ext.go [hunk 4]
```diff
@@ -0,0 +1,160 @@
...
+
+	for name, ext := range exts {
+		result[name] = ext
+	}
+
+	return result
+}
+
+// GetAll returns all extensions, sorted by their import path and name.
+func GetAll() []*Extension {
```
Comment (olegbespalov) [inline ext/ext.go:99]: Maybe `List` ?

**Review by olegbespalov — COMMENTED** [review]
I love that PR :heart_eyes: 

I left a couple of comments in PR and have one more general.

Although an extension output looks excellent, there are no questions for the `k6 version`. 

But I feel it's not always relevant to have the same level of details (precisely version and repository) for the `k6 run` :thinking: I had an impression that we tend to keep it minimal.

File: ext/ext.go (hunk 2 above)
Comment (imiric) [reply ext/ext.go]: Sure. Done in 6de4f4eb7.

I'm slightly against "module" (or "mod") though, since in the case of outputs, it's actually a function, but :man_shrugging:

File: cmd/ui.go (hunk 1 above)
Comment (imiric) [reply cmd/ui.go:412]: :thinking: This is a bit more involved than what formatting would imply, so I think I prefer keeping it as `get*`, if you don't mind.

Otherwise, please state your case. :slightly_smiling_face:

File: ext/ext.go (hunk 3 above)
Comment (imiric) [reply ext/ext.go:125]: What's wrong with `get*`? You really don't seem to like that word :smile: 

Sure, "extract" could be used here as well, but "get" is a standard name, and is clear enough IMO. :man_shrugging:

File: ext/ext.go [hunk 5]
```diff
@@ -0,0 +1,160 @@
...
+	mx         sync.RWMutex
+	extensions = make(map[ExtensionType]map[string]*Extension)
+)
+
+// ExtensionType is the type of all supported k6 extensions.
+type ExtensionType uint8
+
+// All supported k6 extension types.
+const (
+	JSExtension ExtensionType = iota + 1
```
Comment (oleiade) [inline ext/ext.go:26]: That looks like an opportunity to learn something: why the `+1` on the `iota` here? 😇

File: ext/ext.go [hunk 6]
```diff
@@ -0,0 +1,160 @@
...
+	OutputExtension
+)
+
+func (e ExtensionType) String() string {
+	var s string
+	switch e {
+	case JSExtension:
+		s = "js"
+	case OutputExtension:
+		s = "out"
```
Comment (oleiade) [inline ext/ext.go:36]: UX nit: I would find "output" to be more explicit, especially if we show this to the user. "out" is quite a polysemic word, used in a ton of different contexts, and as a user, I think I could be confused/unclear by what it refers to.

File: ext/ext.go [hunk 7]
```diff
@@ -0,0 +1,160 @@
...
+	}
+	return s
+}
+
+// Extension is a generic container for any k6 extension.
+type Extension struct {
+	Name, Path, Version string
+	Type                ExtensionType
+	Module              interface{}
```
Comment (oleiade) [inline ext/ext.go:45]: This comment might be caused by the fact that I'm only partially through the PR, but I must admit that looking at this field's definition and how it's used in `Register` as a user, I would be unclear as to what kind of value I should use to set the `Module` field.

**Review by oleiade — APPROVED** [review]
Really great work @imiric 👍🏻 🎉 🦖 

I'm also super happy to see this happen! I left a couple of nitpicks for your consideration, but I wouldn't consider any of them blocking in any way. Personally, I don't  necessarily mind the `k6 run` output as it is now 🙇🏻

File: ext/ext.go (hunk 3 above)
Comment (olegbespalov) [reply ext/ext.go:125]: No, I'm not against the `get*`, but the truth is that it's too generic, and if it's possible to provide a more precise name, it will be better since it saves time for a code reader.

I have a feeling that extract can tell more to the end user than the `get`, since, from the method name user already can understand that we're extracting details from the first argument without jumping to the method body.

Comment (imiric) [reply ext/ext.go]: I see, that makes sense. I renamed it to `extractModuleInfo` in b1f3c94b6.

File: cmd/ui.go (hunk 1 above)
Comment (imiric) [reply cmd/ui.go]: Following your argument about `get` being too generic below, I also renamed this to `formatExtensionsDescription` in 37b0e1e95.

File: ext/ext.go (hunk 5 above)
Comment (imiric) [reply ext/ext.go:26]: Just a convention to avoid constants with a value of 0. That way you can identify when a value was set or not.

File: ext/ext.go [hunk 8]
```diff
@@ -0,0 +1,160 @@
...
+	case OutputExtension:
+		s = "out"
+	}
+	return s
+}
+
+// Extension is a generic container for any k6 extension.
+type Extension struct {
+	Name, Path, Version string
+	Type                ExtensionType
```
[the remark this answers is not in the document]
Comment (imiric) [reply ext/ext.go:44]: :thinking: I think we've always referred to these as extension "types", so I wouldn't want to change our vocabulary just because it's a reserved keyword. Though in this case `type` is the keyword, and `Type` works just fine, so I'd rather keep calling it this, if you don't mind.

File: ext/ext.go (hunk 7 above)
Comment (imiric) [reply ext/ext.go:45]: Sure, it is confusing. :disappointed: We initially called this "module" when JS extensions were introduced, as JS extensions would register a struct of their JS module. But then we changed the API for output extensions and had them register a constructor function that would return a module, for initialization purposes. In retrospect, I think this was the wrong API to introduce, but since I doubt we'll change this, every extension type is now free to choose what works best.

Since I can't think of a more generic name that would fit better, I'm inclined to leave it as `Module`.

**Comment by na--** [comment]
My vote would be to show extension information only in `k6 version`, but not in `k6 run` :thinking_face: Maybe we can add a `debug`-level log message with that information in all other commands (`k6 run`, `k6 archive`, `k6 inspect`), but that's it 

`k6 run` is already quite noisy, so we shouldn't add more things in there that might be completely unconnected to the actual test run :thinking:  Whatever extensions were compiled into the current k6 binary, there is no guarantee that they are being used at the moment. Besides, we don't show the k6 version, why should we show the extensions that were bundled in it?
