### PR TITLE
Fix position parser for base pointer options

### LINKED ISSUE #4429: tap position option doesn't offset the position as requested
Tested against: https://github.com/grafana/xk6-browser/commit/dbede120c63df43995813a847a25b0e66e289592

Using `position` option on `locator` methods that has it doesn't offset the position as requested.

In the below code it works against `localhost:8080`, which is a test server that can be found here with instructions on how to run it locally: https://github.com/ankur22/testserver.

```javascript
import { sleep } from 'k6';
import launcher from 'k6/x/browser';

export default function () {
  const browser = launcher.launch('chromium', {
    headless: false,
  });
  const context = browser.newContext();
  const page = context.newPage();
  const res = page.goto('http://localhost:8080/other');
  const l = page.locator('#cars-options');
  sleep(1);
  l.tap({
    position: {
      x: 0,
      y: 40
    }
  });

  sleep(10);
  browser.close();
}
```

In the test above, it should select the third option in the `select` menu, but it always selects the first option.

### PR DESCRIPTION
**Pull request by chrismooreproductions**
Fixes an incorrect error check in parsing logic

    Closes #4429

## What?

Fixes an incorrect error check in the parser code for the `position` option, with an example of the correct functionality.

## Why?

As in #4429, the `position` options weren't being correctly parsed meaning `tap()` always tapped at position (0,0).

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests for my changes.
- [x] I have run linter and tests locally (`make check`) and all pass.

## Checklist: Documentation (only for k6 maintainers and if relevant)

**Please do not merge this PR until the following items are filled out.**

- [ ] I have added the correct milestone and labels to the PR.
- [ ] I have updated the release notes: _link_
- [ ] I have updated or added an issue to the [k6-documentation](https://github.com/grafana/k6-docs): grafana/k6-docs#NUMBER if applicable
- [ ] I have updated or added an issue to the [TypeScript definitions](https://github.com/grafana/k6-DefinitelyTyped/tree/master/types/k6): grafana/k6-DefinitelyTyped#NUMBER if applicable

## Related PR(s)/Issue(s)

Closes #4429

### CODE REVIEW

File: examples/browser/tap-position.js [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+    
+    await check(page.locator('#select-multiple-info-display'), {
+      'displays correctly tapped value': async lo => {
+        return await lo.textContent().trim() === 'Selected: three'
+      }
+    })
+  } finally {
+    await page.close()
+  }
+}
```
Comment (chrismooreproductions) [inline examples/browser/tap-position.js]: I don't think this example is technically required, but it looks like we don't have explicit tests for the element handle options, and this highlights the working functionality.

**Comment by oleiade** [comment]
@ankur I'll dismiss myself in your favor as you opened that issue if that's okay with you 🙇🏻

File: examples/browser/tap-position.js (hunk 1 above)
Comment (ankur22) [reply examples/browser/tap-position.js]: I would prefer an integration test, or even just a unit test. Since the issue was in the `Parse` logic maybe we should have a unit test on that, and then an integration test in the `tests` package to ensure that we don't regress in the future.

File: internal/js/modules/k6/browser/common/element_handle_options.go [hunk 2]
```diff
@@ -188,7 +188,7 @@ func (o *ElementHandleBasePointerOptions) Parse(ctx context.Context, opts sobek.
 			case "position":
 				var p map[string]float64
 				o.Position = &Position{}
-				if rt.ExportTo(opts.Get(k), &p) != nil {
+				if rt.ExportTo(opts.Get(k), &p) == nil {
```
Comment (ankur22) [inline internal/js/modules/k6/browser/common/element_handle_options.go]: I like easy fixes 😄 Thanks!

Comment (chrismooreproductions) [reply internal/js/modules/k6/browser/common/element_handle_options.go]: Ha!

I went down a bit of a rabbit hole with the sobek types but the fix was simple in the end :)

File: examples/browser/tap-position.js (hunk 1 above)
Comment (chrismooreproductions) [reply examples/browser/tap-position.js]: No problem. I may look to expand this PR to cover a few other cases as discussed in #4413, and I had a thought that I can introduce some unit tests along the way.

Leave it with me (and thanks for the review 🫶)

File: internal/js/modules/k6/browser/common/element_handle_options.go (hunk 2 above)
Comment (AgnesToulet) [reply internal/js/modules/k6/browser/common/element_handle_options.go]: @ankur22 Shouldn't we follow the same pattern as in the other functions and return the error if it's not nil?
Something like (not applicable directly as I moved line 190 after the error check:
```suggestion
				if err := rt.ExportTo(opts.Get(k), &p); err != nil {
					return fmt.Errorf("parsing element handle base pointer option position: %w", err)
				}
				o.Position = &Position{}
				o.Position.X = p["x"]
				o.Position.Y = p["y"]
```

Comment (ankur22) [reply internal/js/modules/k6/browser/common/element_handle_options.go]: Yes correct! Good spot! @chrismooreproductions please take a look at what @AgnesToulet has pointed out. You should be able to find other examples in the codebase where we are doing this, as well as the suggestion itself.

Comment (chrismooreproductions) [reply internal/js/modules/k6/browser/common/element_handle_options.go]: N/P thanks Agnes! I will fix this up and get back to you shortly

Comment (chrismooreproductions) [reply internal/js/modules/k6/browser/common/element_handle_options.go]: Hey guys sorry for the delay on this, I have pushed the suggested change. Nice catch Agnes :)

File: examples/browser/tap-position.js (hunk 1 above)
Comment (chrismooreproductions) [reply examples/browser/tap-position.js]: Hi @ankur22 , hope you are well!

Sorry for the delay, I have pushed the suggested changes and deleted this file.

If you could review when you get that chance that would be fab.

Thanks!

Chris

Comment (ankur22) [reply examples/browser/tap-position.js]: Brilliant, thanks! Can you merge in the latest master please?

Comment (chrismooreproductions) [reply examples/browser/tap-position.js]: Sure thing ill do that this evening 👍

Comment (chrismooreproductions) [reply examples/browser/tap-position.js]: Hi @ankur22 sorry for the delay on this, I've had a few things going on.

I've rebased on master and it's ready for you to merge :)

Let me know if I can do anything else to help.
