### PR TITLE
gRPC: Stop using protoregistry.GlobalTypes

### LINKED ISSUE #3961: gRPC using reflect race on registering types
### Brief summary

We have tests that use `constant-arrival-rate` executor against a number of grpc applications.  We are using reflection.  Most of these run fine.  Against some applications, we occasionally receive a panic:

```
panic: proto: message proto.com.XXXXX.XXXXX.XXXXX.MyService1 is already registered
```
This is not completely deterministic.  However, for applications where it occurs, the probability increases as we increase `rate`.

As a workaround we are switching these tests to `ramping-arrival-rate`, but ideally we would like to be able to use `constant-arrival-rate`.

(I've obfuscated actual host and service names in all output)

### k6 version

v0.53.0 

### OS

Mariner 2.0.20240628

### Docker version and image (if applicable)

n/a

### Steps to reproduce the problem

version:

```
$ k6 --version
k6 v0.53.0 (go1.23.1, linux/amd64)
Extensions:
  github.com/grafana/xk6-sql v0.4.1, k6/x/sql [js]
  github.com/mostafa/xk6-kafka v0.27.0, k6/x/kafka [js]
  github.com/thotasrinath/xk6-couchbase v0.0.8, k6/x/couchbase [js]
```

OS:
```
$ cat lsb-release 
DISTRIB_ID="Mariner"
DISTRIB_RELEASE="2.0.20240628"
DISTRIB_CODENAME=Mariner
DISTRIB_DESCRIPTION="CBL-Mariner 2.0.20240628"

$ cat mariner-release 
CBL-Mariner 2.0.20240628
MARINER_BUILD_NUMBER=baf1849

$ uname -a
Linux XXXX-XX999.XXX.XXXX.com 5.15.160.1-1.cm2 #1 SMP Fri Jun 28 10:31:37 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

Simple test script.   See attached for script and output from several runs.  Note the panic line may show different grpc endpoints, it doesn't always show the same one (I gather this is related to reflection).

```
$ /path/to/k6/intel/k6 run   /tmp/XXXXX/k6.js  

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io

     execution: local
        script: /tmp/XXXXX/k6.js
        output: -

     scenarios: (100.00%) 1 scenario, 50 max VUs, 35s max duration (incl. graceful stop):
              * constant-qps: 20000.00 iterations/s for 5s (maxVUs: 50, gracefulStop: 30s)

WARN[0000] Insufficient VUs, reached 50 active VUs and cannot initialize more  executor=constant-arrival-rate scenario=constant-qps
panic: proto: message proto.com.XXXX.XXXX.XXXX.SomeServiceName is already registered
```

### Expected behaviour

Test executes.

### Actual behaviour

See attached output files.
 [k6.js.txt](https://github.com/user-attachments/files/17048244/k6.js.txt)
[k6.out.1.txt](https://github.com/user-attachments/files/17048247/k6.out.1.txt)
[k6.out.2.txt](https://github.com/user-attachments/files/17048246/k6.out.2.txt)
[k6.out.3.txt](https://github.com/user-attachments/files/17048245/k6.out.3.txt)

### PR DESCRIPTION
**Pull request by joanlopez**
## What?

Introduce the following changes:
- (a) stop using `protoregistry.GlobalTypes` for `grpc.Client.load`, in favor of client-specific ones.
- (b) combined with the use of a `sync.Mutex` per client.

## Why?

To:
- (a) reduce chances of racing on concurrent registrations of the same types - see #3961.
- (b) to prevent concurrent calls of `client.load` to the same client instance from competing/racing.

## Checklist

- [X] I have performed a self-review of my code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests for my changes.
- [ ] I have run linter and tests locally (`make check`) and all pass.

## Checklist: Documentation (only for k6 maintainers and if relevant)

**Please do not merge this PR until the following items are filled out.**

- [ ] I have added the correct milestone and labels to the PR.
- [ ] I have updated the release notes: _link_
- [ ] I have updated or added an issue to the [k6-documentation](https://github.com/grafana/k6-docs): grafana/k6-docs#NUMBER if applicable
- [ ] I have updated or added an issue to the [TypeScript definitions](https://github.com/grafana/k6-DefinitelyTyped/tree/master/types/k6): grafana/k6-DefinitelyTyped#NUMBER if applicable

## Related PR(s)/Issue(s)

Closes #3961

### CODE REVIEW

File: internal/js/modules/k6/grpc/client_test.go [hunk 1]
```diff
@@ -1597,3 +1606,16 @@ func TestClientConnectionReflectMetadata(t *testing.T) {
...
+	t.Helper()
+
+	client, ok := val.Export().(*k6grpc.Client)
+	require.True(t, ok, "got: %T, want *k6grpc.Client", client)
+
+	clientValue := reflect.ValueOf(client).Elem()
+	typesField := clientValue.FieldByName("types")
+
+	typesField = reflect.NewAt(typesField.Type(), unsafe.Pointer(typesField.UnsafeAddr())).Elem()
+	return typesField.Interface().(*protoregistry.Types)
```
Comment (joanlopez) [inline internal/js/modules/k6/grpc/client_test.go]: I know this type of magic is generally discouraged, but I hope it's fine as long as it's used only for testing purposes.

The other alternatives I could think of were:
- Renaming the test package name, from `grpc_test` to `grpc` to have access to `Client` private attributes/methods, _but I think it's useful to leave it as-is as long as we can._ 
- Exposing the `types` attribute or some of its methods publicly, _which at the beginning I thought it could also be a valid approach as long as the package lives under `internal`, but then realized that public methods are automatically exposed to the JS layer, so likely a no-go._ 

So, finally I decided that this is the least painful approach.

File: internal/js/modules/k6/grpc/client.go [hunk 2]
```diff
@@ -516,6 +520,13 @@ func (c *Client) convertToMethodInfo(fdset *descriptorpb.FileDescriptorSet) ([]M
 			FullMethod: name,
 		})
 	}
+
+	// We want to avoid concurrent calls to client.load competing
+	// for registering types, as they may end up panicking if they
+	// try to register the same types.
+	c.typesMtx.Lock()
+	defer c.typesMtx.Unlock()
```
Comment (joanlopez) [inline internal/js/modules/k6/grpc/client.go:528]: Correct me if I'm wrong, but I think we could still have panics if we don't prevent two concurrent calls to `client.load` from competing, although arguably that's less likely, and most of the cases seen so far are likely due to the use of global types.

Comment (mstoykov) [reply internal/js/modules/k6/grpc/client.go:528]: As load has to open files it needs to be called in hte first init context, before we stop loading anything from the filesystem.

As such I do think this is unlikely to have any problems, but I am not against keeping hte mutex here

**Review by mstoykov — DISMISSED** [review]

**Review by inancgumus — COMMENTED** [review]
[Here](https://github.com/grafana/k6/pull/5017#discussion_r2260035931), you don't have to change the package `grpc_test` to `grpc` or export `types` in the code. Instead, you can add a test-only exported `Types` method and call that method in tests (without exposing it to the non-test code).

To do that, create the following `client_export_test.go` file:

```go
package grpc // <- important

import "google.golang.org/protobuf/reflect/protoregistry"

// Types is exported only for testing purposes.
func (c *Client) Types() *protoregistry.Types {
	return c.types
}
```

You can then get `Client.Types` from tests:

```go
client, ok := val.Export().(*k6grpc.Client)
require.True(t, ok, "got: %T, want *k6grpc.Client", client)
return client.Types() // no reflection is needed
```

`Client.Types()` will be available only in tests.

**Comment by joanlopez** [comment]
Right, thanks! @inancgumus

I'm pretty sure I have used that "trick" before, for similar purposes, but this time I wasn't that inspired.
Thanks for suggesting it, much cleaner! 🙌🏻

**Review by mstoykov — APPROVED** [review]
