### PR TITLE
`console.log`: Deep object logging

### LINKED ISSUE #5429: Console log objects with classes and functions
### Brief summary

Let's say we have Class1 and Class2.
If you try to console.log({ Class1, Class2 }) the output in the console will be {}. 
The bug is observed only when the property is js class.

### k6 version

1.4.0 - commit/a9f9e3b28a, go1.25.4

### OS

Ubuntu 20.04.6

### Docker version and image (if applicable)

_No response_

### Steps to reproduce the problem

Run the script below and check the console.error(): `k6 run script.js`
```
const DummyOne = class DummyOne {
  get() {
    return 'DummyOne';
  }
};
const DummyTwo = class DummyTwo {
  get() {
    return 'DummyTwo';
  }
};
const string = 'str';
const int = 4;

console.log(string);
console.log(int);
console.log('str + int obj ->\n', { string, int });

console.log('---------');

console.log(DummyOne);
console.log(DummyTwo);
const classesObj = { DummyOne, DummyTwo };
console.error('FAIL: classes obj ->\n', classesObj);
console.log('Try accessing property ->\n', classesObj.DummyOne.name);

Object.values(classesObj).forEach((val) => {
  console.log('foreach logging ->\n', val.name);
});

export default function () {
}
```

### Expected behaviour

Line 23: `console.error('FAIL: classes obj ->\n', classesObj);` prints `{ DummyOne: [object Function], DummyTwo: [object Function]} `

### Actual behaviour

Line 23: `console.error('FAIL: classes obj ->\n', classesObj);` prints `{}`

### PR DESCRIPTION
**Pull request by inancgumus**
## What?

Console logging now properly traverses and displays complex JavaScript structures:

```js
console.log({ one: class {}, two: function() { } });
// Before: {}
// After:  {"one":"[object Function]","two":"[object Function]"}

console.log([{ handler: class {} }, { data: [1, 2, class {}] }])
// Before: [{},{"data":[1,2,null]}]
// After:  [{"handler":"[object Function]"},{"data":[1,2,"[object Function]"]}]

console.log({
    a: [1, 2, 3],
    b: class { },
    c: () => { },
    d: function () { },
    e: [1, () => { }, function () { }, class { }, 2],
})
// Before: {"a":[1,2,3],"e":[1,null,null,null,2]}
// After:  {"a":[1,2,3],"b":"[object Function]","c":"[object Function]","d":"[object Function]","e":[1,"[object Function]","[object Function]","[object Function]",2]}
```

Improved circular object detection:

```js
console.log(function() {
    var a = {
        fn: function() {},
        foo: {}
    };
    a.foo = a;
    return a
}())
// Before: [object Object]
// After:  {"fn":"[object Function]","foo":"[Circular]"}
```

## Why?

Sobek's JSON marshaling marshals nested properties like functions and classes to `{}`, `null`, or silently skips them, making debugging painful. Now we recursively traverse the entire object tree, properly marking functions and classes, producing more meaningful output.

## Note

Object keys are sorted alphabetically because [Go's JSON marshaling](https://pkg.go.dev/encoding/json#Marshal).

## Benchmarks

The new `console.log`'s cost is negligible in realistic scenarios.

Here are the results from a test with 100 VUs for 10m:

| Branch  | Real Time | User CPU | Sys CPU | Max Resident | Iterations/s |
|---------|-----------|----------|---------|--------------|--------------|
| master  | 11.70s    | 1.65s    | 0.59s   | 107.1 MB     | 87.26/s      |
| this    | 11.57s    | 1.63s    | 0.53s   | 108.6 MB     | 87.90/s      |

<details>
<summary>
See the script used for testing.
</summary>

```js
// Combined k6 test: realistic HTTP I/O + artificial complex objects
// Tests console.log with both API responses and predefined objects
import http from "k6/http";
import { check, group } from "k6";

const BASE_URL = "https://quickpizza.grafana.com";

// Artificial objects from console_bench_script.js
const simpleObject = { name: "test", value: 42, active: true };

const nestedObject = {
    user: {
        id: 12345,
        profile: {
            name: "John Doe",
            email: "john@example.com",
            settings: {
                theme: "dark",
                notifications: true,
                language: "en-US"
            }
        }
    },
    metadata: {
        created: "2024-01-15T10:30:00Z",
        updated: "2024-01-20T14:22:00Z",
        version: 3
    }
};

const arrayWithObjects = [
    { id: 1, name: "Item 1", tags: ["a", "b", "c"] },
    { id: 2, name: "Item 2", tags: ["d", "e"] },
    { id: 3, name: "Item 3", tags: ["f", "g", "h", "i"] },
    { id: 4, name: "Item 4", tags: [] },
    { id: 5, name: "Item 5", tags: ["j"] }
];

const deeplyNested = {
    level1: {
        level2: {
            level3: {
                level4: {
                    level5: {
                        level6: {
                            level7: {
                                level8: {
                                    level9: {
                                        level10: {
                                            value: "deep",
                                            count: 100
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
};

const wideObject = {};
for (let i = 0; i < 50; i++) {
    wideObject[`key_${i}`] = {
        index: i,
        value: `value_${i}`,
        nested: { a: i * 2, b: i * 3 }
    };
}

const mixedComplex = {
    strings: ["hello", "world", "test", "benchmark"],
    numbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    objects: [
        { x: 1, y: 2 },
        { x: 3, y: 4 },
        { x: 5, y: 6 }
    ],
    nested: {
        data: {
            items: [
                { id: 1, info: { name: "a", count: 10 } },
                { id: 2, info: { name: "b", count: 20 } },
                { id: 3, info: { name: "c", count: 30 } }
            ]
        }
    },
    metadata: {
        timestamp: "2024-01-01T00:00:00Z",
        source: "benchmark",
        version: "1.0.0"
    }
};

export function setup() {
    const username = `user_${Date.now()}`;
    const password = "testpass123";

    const registerRes = http.post(`${BASE_URL}/api/users`, JSON.stringify({
        username: username,
        password: password
    }), { headers: { "Content-Type": "application/json" } });
    console.log("Registration response:", registerRes.json());

    const loginRes = http.post(`${BASE_URL}/api/users/token/login`, JSON.stringify({
        username: username,
        password: password
    }), { headers: { "Content-Type": "application/json" } });
    const loginData = loginRes.json();
    console.log("Login response:", loginData);

    return { token: loginData.token };
}

export default function (data) {
    const headers = {
        "Content-Type": "application/json",
        "Authorization": `Token ${data.token}`
    };

    // 1. Log artificial objects
    group('Artificial Objects', () => {
        console.log("Simple:", simpleObject);
        console.log("Nested:", nestedObject);
        console.log("Array with objects:", arrayWithObjects);
        console.log("Deeply nested:", deeplyNested);
        console.log("Wide object:", wideObject);
        console.log("Mixed complex:", mixedComplex);
        console.log("Multiple:", simpleObject, nestedObject, arrayWithObjects);
        console.log("Mixed types:", 42, "string", true, simpleObject, [1, 2, 3]);
    });

    // 2. GET pizza with function added
    group('Get Pizza', () => {
        const res = http.post(`${BASE_URL}/api/pizza`, "{}", { headers });
        const passed = check(res, { "pizza ok": (r) => r.status === 200 });
        if (passed) {
            const pizza = res.json();
            pizza.getCalories = function () { return this.calories; };
            console.log("Pizza response:", pizza);
        }
    });

    // 3. GET tools with circular reference
    group('Get Tools', () => {
        const res = http.get(`${BASE_URL}/api/tools`, { headers });
        const passed = check(res, { "tools ok": (r) => r.status === 200 });
        if (passed) {
            const toolsData = { name: "tools", items: res.json().tools };
            toolsData.self = toolsData;
            console.log("Tools with circular:", toolsData);
        }
    });

    // 4. GET doughs with nested circular reference
    group('Get Doughs', () => {
        const res = http.get(`${BASE_URL}/api/doughs`, { headers });
        const passed = check(res, { "doughs ok": (r) => r.status === 200 });
        if (passed) {
            const doughsData = { name: "doughs", items: res.json().doughs };
            doughsData.parent = { child: doughsData, getName: () => "doughs" };
            console.log("Doughs with nested circular:", doughsData);
        }
    });
}

export function teardown(data) {
    http.post(`${BASE_URL}/api/users/token/logout`, null, {
        headers: { "Authorization": `Token ${data.token}` }
    });
    console.log("Logged out");
}
```

</details>

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests for my changes.
- [x] I have run linter and tests locally (`make check`) and all pass.

## Checklist: Documentation (only for k6 maintainers and if relevant)

**Please do not merge this PR until the following items are filled out.**

- [x] I have added the correct milestone and labels to the PR.
- [ ] I have updated the release notes: _link_
- [ ] I have updated or added an issue to the [k6-documentation](https://github.com/grafana/k6-docs): grafana/k6-docs#NUMBER if applicable

## Related PR(s)/Issue(s)

- Fixes #5429
- #5469

### CODE REVIEW

File: internal/js/console.go [hunk 1]
```diff
@@ -98,20 +100,87 @@ func (c console) valueString(v sobek.Value) string {
...
+		if mv, ok = c.traverseValue(obj, make(map[*sobek.Object]bool)); !ok {
+			// We can't marshal circular references.
 			return v.String()
 		}
 	}
-
-	mv, ok := v.(json.Marshaler)
-	if !ok {
-		return v.String()
+	if !isObj {
```
Comment (AgnesToulet) [inline internal/js/console.go:107]: This should be an `else` clause instead.

File: internal/js/console.go [hunk 2]
```diff
@@ -98,20 +100,87 @@ func (c console) valueString(v sobek.Value) string {
...
 	}
 
-	if sobekObj, isObj := v.(*sobek.Object); isObj {
-		if sobekObj.ClassName() == "Error" {
+	var (
+		mv any // either marshal from Sobek or Go
+		ok bool
+	)
+	obj, isObj := v.(*sobek.Object)
+	if isObj {
```
Comment (AgnesToulet) [inline internal/js/console.go]: I personally prefer to have this on one line when possible but no strong opinion: 
```suggestion
	if obj, isObj := v.(*sobek.Object); isObj {
```

File: internal/js/console.go [hunk 3]
```diff
@@ -98,20 +100,87 @@ func (c console) valueString(v sobek.Value) string {
...
+		return functionLog, true
+	}
+	// Skip non-object values.
+	obj, ok := v.(*sobek.Object)
+	if !ok {
+		return v, true
+	}
+	// Prevent circular references.
+	if seen[obj] {
+		return nil, false
```
Comment (AgnesToulet) [inline internal/js/console.go]: Would it be possible to log a warning or maybe ` [object Object] - could not parse object with circular references` instead of just `[object Object]`?

I know it happened to me a lot when debugging JS code and trying to log objects that I know nothing about to discover they contain circular refs when trying to marshal them for example. It could be very confusing to be able to properly display one object and not another without any explanation about why.

**Review by AgnesToulet — APPROVED** [review]
LGTM, left some minor suggestions.

File: internal/js/console.go (hunk 2 above)
Comment (inancgumus) [reply internal/js/console.go]: I've improved circular reference detection and am now using a different code.

File: internal/js/console.go (hunk 1 above)
Comment (inancgumus) [reply internal/js/console.go:107]: It's a stylistic preference. I've changed the algo.

File: internal/js/console.go (hunk 3 above)
Comment (inancgumus) [reply internal/js/console.go]: Thanks for the useful suggestion 🙇 I've greatly simplified the algorithm by returning `[Circular]` for circular objects. This also allows us to print objects more accurately than before. I didn't go with `[object Object]` because that won't tell us what's happening, which was your main point.

**Comment by inancgumus** [comment]
@oleiade I like the idea! 🙇 I've created [a new issue](https://github.com/grafana/k6/issues/5469) to tackle it next. If we can merge this PR, I can build the next one based on this to continue improving it.

**Comment by oleiade** [comment]
Perfect, all good by me then 🚀
