### PR TITLE
Fix panic when assign to nil header and cookie when host is not found

### LINKED ISSUE #5213: Panic when assining not a map on an null object
### Brief summary

```javascript
import http from 'k6/http'

export default function () {
  let response = http.get(`https://test.k6.i`)
  response.headers["key"] = "value"
}
```

### k6 version

v1.3.0

### OS

linux

### Docker version and image (if applicable)

_No response_

### Steps to reproduce the problem

run 
```javascript
import http from 'k6/http'

export default function () {
  let response = http.get(`https://test.k6.i`)
  response.headers["key"] = "value"
}

```

### Expected behaviour

Exception

### Actual behaviour

Panic
```
github.com/grafana/sobek.(*Runtime).runWrapped.func1()
        github.com/grafana/sobek@v0.0.0-20250723111835-dd8a13f0d439/runtime.go:2521 +0xe5
panic({0x1afd440?, 0x319b910?})
        runtime/panic.go:783 +0x132
github.com/grafana/sobek.(*vm).handleThrow(0xc0001b18c0, {0x1afd440, 0x319b910})
        github.com/grafana/sobek@v0.0.0-20250723111835-dd8a13f0d439/vm.go:847 +0x425
github.com/grafana/sobek.(*vm).try.func1()
        github.com/grafana/sobek@v0.0.0-20250723111835-dd8a13f0d439/vm.go:866 +0x3f
panic({0x1afd440?, 0x319b910?})
        runtime/panic.go:783 +0x132
github.com/grafana/sobek.(*vm).handleThrow(0xc0001b18c0, {0x1afd440, 0x319b910})
        github.com/grafana/sobek@v0.0.0-20250723111835-dd8a13f0d439/vm.go:847 +0x425
github.com/grafana/sobek.(*vm).runTryInner.func1()
        github.com/grafana/sobek@v0.0.0-20250723111835-dd8a13f0d439/vm.go:889 +0x3f
panic({0x1afd440?, 0x319b910?})
        runtime/panic.go:783 +0x132
reflect.mapassign_faststr0(0x1b3f320, 0xc00089b278?, {0xc0000108e0?, 0xc0004e0750?}, 0xc0004e0750)
        runtime/map_swiss.go:264 +0x25
reflect.mapassign_faststr(0x1a42020?, 0xc0004e0750?, {0xc0000108e0, 0x3}, 0x19?)
        reflect/value.go:3686 +0xa5
reflect.Value.SetMapIndex({0x1b3f320?, 0xc0005c0910?, 0xc000483f10?}, {0x1a42020, 0xc0004e0730, 0x98}, {0x1a42020, 0xc0004e0750, 0x198})
        reflect/map_swiss.go:427 +0x225
github.com/grafana/sobek.(*objectGoMapReflect)._put(0xc000262a00, {0x1a42020, 0xc0004e0730, 0x98}, {0x2197cc0?, 0xc000483f10?}, 0x1)
        github.com/grafana/sobek@v0.0.0-20250723111835-dd8a13f0d439/object_gomap_reflect.go:116 +0x131
github.com/grafana/sobek.(*objectGoMapReflect).setOwnStr(0xc000262a00, {0xc0000108e0, 0x3}, {0x2197cc0, 0xc000483f10}, 0x1)
        github.com/grafana/sobek@v0.0.0-20250723111835-dd8a13f0d439/object_gomap_reflect.go:147 +0x25c
github.com/grafana/sobek.setPropStrictP.exec({0xc0000108e0?, 0xc000483f10?}, 0xc0001b18c0)
        github.com/grafana/sobek@v0.0.0-20250723111835-dd8a13f0d439/vm.go:2400 +0x8a
github.com/grafana/sobek.(*vm).run(0xc0001b18c0)
        github.com/grafana/sobek@v0.0.0-20250723111835-dd8a13f0d439/vm.go:642 +0x5b
github.com/grafana/sobek.(*vm).runTryInner(0xc0001b18c0?)
        github.com/grafana/sobek@v0.0.0-20250723111835-dd8a13f0d439/vm.go:893 +0x52
github.com/grafana/sobek.(*baseJsFuncObject).__call(0xc00038f8c0, {0xc0007041a0?, 0x1, 0x1cb84a0?}, {0x0, 0x0}, {0x2197f20?, 0x3207b40?})
        github.com/grafana/sobek@v0.0.0-20250723111835-dd8a13f0d439/func.go:434 +0x711
github.com/grafana/sobek.(*baseJsFuncObject)._call(...)
        github.com/grafana/sobek@v0.0.0-20250723111835-dd8a13f0d439/func.go:450
github.com/grafana/sobek.(*baseJsFuncObject).call(0x7f1f60caa3e8?, {{0x2197f20, 0x3207b40}, {0xc0007041a0, 0x1, 0x1}}, {0x0?, 0x0?})
        github.com/grafana/sobek@v0.0.0-20250723111835-dd8a13f0d439/func.go:458 +0x6d
github.com/grafana/sobek.(*baseJsFuncObject).Call(...)
        github.com/grafana/sobek@v0.0.0-20250723111835-dd8a13f0d439/func.go:390
github.com/grafana/sobek.AssertFunction.func1.1()
        github.com/grafana/sobek@v0.0.0-20250723111835-dd8a13f0d439/runtime.go:2481 +0x56
github.com/grafana/sobek.(*vm).try(0xc0001b18c0, 0xc000909908)
        github.com/grafana/sobek@v0.0.0-20250723111835-dd8a13f0d439/vm.go:870 +0x234
github.com/grafana/sobek.(*Runtime).runWrapped(0xc00037b408, 0x47e585?)
        github.com/grafana/sobek@v0.0.0-20250723111835-dd8a13f0d439/runtime.go:2525 +0x5f
github.com/grafana/sobek.AssertFunction.func1({0x2197f20?, 0x3207b40?}, {0xc0007041a0?, 0x1?, 0x1?})
        github.com/grafana/sobek@v0.0.0-20250723111835-dd8a13f0d439/runtime.go:2480 +0x8c
go.k6.io/k6/internal/js.(*VU).runFn.func2()
        go.k6.io/k6/internal/js/runner.go:922 +0x3e
go.k6.io/k6/internal/js/eventloop.(*EventLoop).Start(0xc000030050, 0xc00090a3c0)
        go.k6.io/k6/internal/js/eventloop/eventloop.go:179 +0x197
go.k6.io/k6/internal/js.(*VU).runFn(0xc00058dd60, {0x217ff68, 0xc0009140f0}, 0x1, 0xc000918060, 0xc000704180, {0xc0007041a0, 0x1, 0x1})
        go.k6.io/k6/internal/js/runner.go:921 +0x269
go.k6.io/k6/internal/js.(*ActiveVU).RunOnce(0xc00044e040)
        go.k6.io/k6/internal/js/runner.go:854 +0x487
go.k6.io/k6/lib/executor.PerVUIterations.Run.getIterationRunner.func7({0x217ff30, 0xc00090a180}, {0x216de80?, 0xc00044e040?})
        go.k6.io/k6/lib/executor/helpers.go:108 +0x4a
go.k6.io/k6/lib/executor.PerVUIterations.Run.func5({0x21775a8, 0xc00058dd60})
        go.k6.io/k6/lib/executor/per_vu_iterations.go:228 +0x39a
created by go.k6.io/k6/lib/executor.PerVUIterations.Run in goroutine 67
        go.k6.io/k6/lib/executor/per_vu_iterations.go:241 +0xb85
```

### PR DESCRIPTION
**Pull request by chojs23**
## What?

When a request fails, the Response object is still returned but previously the Headers and Cookies maps were nil. 

## Why?

Trying to assign to a nil map causes a panic. Now these maps are always initialized, so users can safely modify them even for failed requests.

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests for my changes.
- [x] I have run linter and tests locally (`make check`) and all pass.

## Checklist: Documentation (only for k6 maintainers and if relevant)

**Please do not merge this PR until the following items are filled out.**

- [ ] I have added the correct milestone and labels to the PR.
- [ ] I have updated the release notes: _link_
- [ ] I have updated or added an issue to the [k6-documentation](https://github.com/grafana/k6-docs): grafana/k6-docs#NUMBER if applicable
- [ ] I have updated or added an issue to the [TypeScript definitions](https://github.com/grafana/k6-DefinitelyTyped/tree/master/types/k6): grafana/k6-DefinitelyTyped#NUMBER if applicable

## Related PR(s)/Issue(s)

Closes #5213

### CODE REVIEW

**Comment by inancgumus** [comment]
Hi @chojs23, thanks for the contribution!

Can you add a test to reproduce this issue to avoid future regressions?

> When a request fails, the Response object is still returned but previously the Headers and Cookies maps were nil. Trying to assign to a nil map causes a panic. Now these maps are always initialized, so users can safely modify them even for failed requests.

**Comment by chojs23** [comment]
Hi @inancgumus, I added some tests.

File: lib/netext/httpext/request.go [hunk 1]
```diff
@@ -229,7 +229,12 @@ func MakeRequest(ctx context.Context, state *lib.State, preq *ParsedHTTPRequest)
 		transport = ntlmssp.Negotiator{RoundTripper: transport}
 	}
 
-	resp := &Response{URL: preq.URL.URL, Request: respReq}
+	resp := &Response{
+		URL:     preq.URL.URL,
+		Request: respReq,
+		Headers: make(map[string]string),
+		Cookies: make(map[string][]*HTTPCookie),
+	}
```
Comment (inancgumus) [inline lib/netext/httpext/request.go:237]: Can you use the `NewResponse` function here? Other than that, your PR is LGTM.

Comment (chojs23) [reply lib/netext/httpext/request.go:237]: @inancgumus Thanks for review!

Comment (AgnesToulet) [reply lib/netext/httpext/request.go:237]: This is actually breaking a test because we expect the body to be null here: https://github.com/grafana/k6/blob/master/js/modules/k6/http/request_test.go#L2256 so I think this should be added in both places.

Comment (inancgumus) [reply lib/netext/httpext/request.go:237]: @chojs23, sure. Can you check @AgnesToulet's suggestion please?

Comment (chojs23) [reply lib/netext/httpext/request.go:237]: @inancgumus Creating Response with `NewResponse` function initialize body with empty array but this could break `TestBinaryResponseWithStatus0` test as @AgnesToulet mentioned. 

Hmm, Can we change the initial body null to empty array? I don't know the original code that creating Response with nil body was intended.

Comment (AgnesToulet) [reply lib/netext/httpext/request.go:237]: I'd prefer to keep the original behavior as users could rely on checking if the response body is null in some cases.

Comment (inancgumus) [reply lib/netext/httpext/request.go:237]: To keep the original behavior, can you revert the last commit? Thank you!

Comment (chojs23) [reply lib/netext/httpext/request.go:237]: Sure, I reverted it.
