### PR TITLE
Warn when http.get or http.head receive extra arguments

### LINKED ISSUE #2823: Display a warning when using `http.get` and `http.head` with more than 2 arguments
### Brief summary

The current prototype of the `http.get` and `http.head` methods can prove to be somewhat error-prone, as they take only two arguments, whereas the other HTTP verb-related methods do take 3. 

Although not a bug per-se, this UX can lead to confusion in scenarios like the one I ran into recently: trying to set headers on an HTTP request. Following the docs examples, I intuitively wrote `http.get('myurl', null, params)` with `params` containing my headers. But the `http.get` method would ignore my params completely, as it would treat the second parameter as `null` params instead of a `null` body.  

### k6 version

v0.40.0

### OS

*

### Docker version and image (if applicable)

_No response_

### Steps to reproduce the problem

import http from "k6/http";
import { check } from "k6";
// import tracing from "k6/x/tracing";

const options = {
  vus: 1,
  iterations: 1,
};

tracing.instrument(http, {
  sampling: 12,
  propagator: "w3c",
  baggage: { "X-My-baggage": "something" },
});

// let client = new tracing.Client();

export default () => {
  const params = {
    headers: {
      "X-My-Header": "something",
    },
  };

  const res = http.get("http://localhost:3434/latency/50ms", null, params);
  check(res, {
    "status is 200": (r) => r.status === 200,
  });
};

### Expected behaviour

It's been discussed internally that to let the user know that this is a misuse of the `http.get` and `http.head` methods, we should emit a warning. Something indicating to the user that they're probably doing something wrong: "beware: the http.get and http.head methods do not take a payload argument" or something along those lines would probably do.

### Actual behaviour

⚔️

### PR DESCRIPTION
**Pull request by moko-poi**
## What?

Emit a warning log when `http.get` or `http.head` are called with more than 2 arguments (url + params).

## Why?

`http.get` and `http.head` only accept `(url, params)`, unlike `http.post` and other HTTP methods which accept `(url, body, params)`. Users commonly write
`http.get(url, null, params)` expecting the same 3-argument signature, which silently ignores the extra params. This warning helps users notice the mistake.

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests for my changes.
- [ ] I have run linter and tests locally (`make check`) and all pass.

## Related PR(s)/Issue(s)

- Previous attempt: #3974 (closed due to unaddressed feedback)

Closes #2823

### CODE REVIEW

**Review by codebien — CHANGES_REQUESTED** [review]
Hey @moko-poi 👋 Thanks for this contribution 🎉 

It seems the linter is complaining, can you address that issue, please? The rest of the code sounds good to me, thanks 🙇

**Comment by moko-poi** [comment]
@codebien Fixed the lll lint errors by splitting the long Warnf calls in http.get/http.head across multiple lines. PTAL 🙏

File: internal/js/runner_test.go [hunk 1]
```diff
@@ -2054,7 +2054,7 @@ func runMultiFileTestCase(t *testing.T, tc multiFileTestCase, tb *httpmultibin.H
 	options := runner.GetOptions()
 	require.Empty(t, options.Validate())
 
-	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
+	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
```
Comment (codebien) [inline internal/js/runner_test.go]: It doesn't sound the good approach, we should find a way to speed-up things here or even better make the test not time-dependent.

However, any change to address it, should live in a dedicated pull request. For this specific pull request we can just retry.

**Review by codebien — CHANGES_REQUESTED** [review]

File: internal/js/runner_test.go (hunk 1 above)
Comment (moko-poi) [reply internal/js/runner_test.go]: @codebien Thanks for the feedback\! You're right, I've reverted the timeout change. I'll retry the CI instead. If the flaky test needs a proper fix, I'll address it in a separate PR.

**Review by codebien — APPROVED** [review]

**Review by joanlopez — APPROVED** [review]
