### PR TITLE
websockets: buffered amount not tracked in ArrayBuffer for typed arrays - fixes #5715

### LINKED ISSUE #5715: WebSocket bufferedAmount isn't tracked for TypedArrays
### Brief summary

WebSocket.send() does not track length TypedArrays in bufferedAmount, resulting in a negative bufferedAmount value.

Introduced in #5358 which fixes #5226 

### k6 version

1.6.1

### OS

Windows 11

### Docker version and image (if applicable)

_No response_

### Steps to reproduce the problem

```ts
import { WebSocket } from "k6/websockets";

export default async function() {
    const ws = new WebSocket(`wss://echo.websocket.org`);
    ws.binaryType = 'arraybuffer';
    ws.addEventListener('open', (event) => {
        const a = new Uint8Array(1024);
        ws.send(a.subarray(0, 10));
        console.log("Buffered Amount", ws.bufferedAmount);
    });

    ws.addEventListener('close', (event) => {
        console.log('Closed', event);
    })
    return new Promise(resolve => {
        ws.addEventListener('message', (event) => {
            if (event.data instanceof ArrayBuffer) {
                console.log("Length", event.data.byteLength);
                ws.close();
                resolve(undefined);
            }
        });
    })
}
```

### Expected behaviour

Should print:
```
Buffered Amount 10
Length 10
```

### Actual behaviour

Prints:
```
Buffered Amount 0
Length 10
```

### PR DESCRIPTION
**Pull request by prakharbirla-ng**
## What?

When sending TypedArrays, bufferedAmount was not incremented.
Fixes the bug introduced in #5358

## Why?

Buffered amount should be tracked when data is added to the queue so that it does not become negative.

## Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests for my changes.
- [ ] I have run linter and tests locally (`make check`) and all pass.

## Checklist: Documentation (only for k6 maintainers and if relevant)

**Please do not merge this PR until the following items are filled out.**

- [x] I have added the correct milestone and labels to the PR.
- [ ] I have updated the release notes: _link_
- [ ] I have updated or added an issue to the [k6-documentation](https://github.com/grafana/k6-docs): grafana/k6-docs#NUMBER if applicable
- [ ] I have updated or added an issue to the [TypeScript definitions](https://github.com/grafana/k6-DefinitelyTyped/tree/master/types/k6): grafana/k6-DefinitelyTyped#NUMBER if applicable

## Related PR(s)/Issue(s)

Closes #5715

### CODE REVIEW

File: internal/js/modules/k6/websockets/websockets_test.go [hunk 1]
```diff
@@ -437,13 +437,16 @@ func TestBinaryType_ArrayBuffer_issue_5226(t *testing.T) {
 		ws.binaryType = "arraybuffer"
 		ws.addEventListener("open", () => {
 			const sent = new Uint8Array(1024)
-			ws.send(sent.subarray(0, 1))
+			ws.send(sent.subarray(0, 10))
+			if (ws.bufferedAmount != 10) {
+				throw "Expected 10 bufferedAmount got "+ ws.bufferedAmount
```
Comment (ankur22) [inline internal/js/modules/k6/websockets/websockets_test.go]: Is there a reason why you're throwing a string instead of a `Error`?

File: internal/js/modules/k6/websockets/websockets_test.go
Comment (ankur22) [inline internal/js/modules/k6/websockets/websockets_test.go:430]: Is there a better place that modifying this test? Maybe a new test would be better?

Also need a test for `DataView`.

**Review by ankur22 — CHANGES_REQUESTED** [review]
Thanks for the fix. I left some comments around what I think would improve the testing of the fix.

File: internal/js/modules/k6/websockets/websockets_test.go (hunk 1 above)
Comment (prakharbirla-ng) [reply internal/js/modules/k6/websockets/websockets_test.go]: Fixed

File: internal/js/modules/k6/websockets/websockets_test.go
Comment (prakharbirla-ng) [reply internal/js/modules/k6/websockets/websockets_test.go:430]: Fixed, augmented the existing test `TestArrayBufferViewSupport` to have a separate pass for `testArrayBufferViewBufferedAmount`. I reused the original runner as it maintains a list of TypedArrays supported by Sobek.

Regarding `DataView`, I found that it isn't supported by this package. Trying to send a DataView invokes this part of the code resulting in an error:
```go
	case map[string]any:
		rt := w.vu.Runtime()
		obj := msg.ToObject(rt)
		if !isBlob(obj, w.blobConstructor) {
			common.Throw(rt, fmt.Errorf("unsupported send type %T", o))
		}
```

File: internal/js/modules/k6/websockets/websockets_test.go [hunk 2]
```diff
@@ -1553,6 +1554,33 @@ func testArrayBufferViewSupport(t *testing.T, viewName string) {
...
+		var ws = new WebSocket("WSBIN_URL/ws-echo")
+		ws.addEventListener("open", () => {
+			const sent = new %[1]s([164, 41])
+			ws.send(sent)
+			if (ws.bufferedAmount != sent.byteLength) {
+				throw new Error("Expected " + sent.byteLength + " bufferedAmount got " + ws.bufferedAmount);
+			}
+			ws.onmessage = async (e) => {
+				const received = new %[1]s(await e.data.arrayBuffer());
+				if (ws.bufferedAmount != 0) {
```
Comment (ankur22) [inline internal/js/modules/k6/websockets/websockets_test.go:1571]: `received` is assigned but never used, can it be removed?

File: internal/js/modules/k6/websockets/websockets_test.go
Comment (ankur22) [reply internal/js/modules/k6/websockets/websockets_test.go:430]: Ok, can you update the issue and PR title/description by removing `DataView`? Thanks!

**Review by ankur22 — APPROVED** [review]

**Review by szkiba — APPROVED** [review]
