### PR TITLE
fix: ensure csv.parse generates a single shared array per file+options

### LINKED ISSUE #5493: csv.parse do not share the array between VUs
### Brief summary

I need to load a CSV to have some random data for my VUs. My CSV is around ~40MB large.

When using csv.parse it seems to create one SharedArray per VU since my RAM usage scales linearly with the VU number.

### k6 version

1.4.0

### OS

Ubuntu 22.04

### Docker version and image (if applicable)

_No response_

### Steps to reproduce the problem

1. Generate a big-ish CSV file (40MB
2. Run k6 with this file
```
import {open} from 'k6/experimental/fs';
import csv from 'k6/experimental/csv';
import {sleep} from "k6";


const csvFile = 'users.csv';
const users = await csv.parse(await open(csvFile), {delimiter: ';', asObjects: true});

export const options = {
    vus: 100,
    duration: '10m',
};
export default function () {
    const user = users[Math.floor(Math.random() * users.length)];
    sleep(10)
}

```
3. compare the result with less VUs

### Expected behaviour

The memory footprint should stay around the same regardless of the number of VUs 

### Actual behaviour

The memory footprint explodes (in my case around 6.5Go used for 100VU and scales with the number of VU)

### Start of analysis 
My guess but I'm not a go expert is that we create the shared array with a "random" name each time and so it's loading the CSV for each VU instead of being a real SharedArray. Code in question: https://github.com/grafana/k6/blob/2082ec59f942e8a0d362969484b38b6fabf78626/internal/js/modules/k6/experimental/csv/module.go#L126

Maybe we need to be able to pass a name to the csv.parse method

### Used workaround
For reference I did the same thing with the same file and the "old" way of loading a csv with papaparse and the other "open" function as a workaround. The parsing is obviously slower since it's done in javascript but the memory footprint is around 0.2Go instead which is way better.

"Old" way script
```
import {sleep} from "k6";
import papaparse from "./papaparse.js"
import {SharedArray} from "k6/data";

const csvFile = 'users.csv';
const users = new SharedArray('users', function () {
    return papaparse.parse(open(csvFile), {header: true, delimiter: ';'}).data;
});
export const options = {
    vus: 100,
    duration: '10m',
};
export default function () {
    const user = users[Math.floor(Math.random() * users.length)];
    sleep(10)
}
```

### PR DESCRIPTION
**Pull request by oleiade**
## What

The csv.parse function was creating a new SharedArray with a random name (based on time.Now().Nanosecond()) for each VU, causing memory usage to scale linearly with VU count instead of sharing data across VUs. For a 40MB CSV file with 100 VUs, this resulted in ~6.5GB memory usage instead of the expected ~200MB.

This commit fixes the issue by:
1. Replacing random SharedArray name generation with deterministic hash-based naming. The name is now derived from the file path and parser options (delimiter, skipFirstLine, fromLine, toLine, asObjects) using SHA256, ensuring the same file+options combination always produces the same SharedArray name.
2. Refactoring the internal sharedArrays structure to use a slot-based system with sync.Once guarantees. This ensures the underlying data is initialized exactly once per unique name, even when multiple VUs call csv.parse concurrently.
3. Adding loadOrStore method that uses double-checked locking to minimize contention while ensuring thread-safe single initialization of shared arrays.

Closes #5493

## Demo

Given a 40MB csv file, and the following script:
```javascript
import { open } from 'k6/experimental/fs'
import csv from 'k6/experimental/csv'
import { scenario } from 'k6/execution'

export const options = {
    vus: 20,
	duration: '10m',
}

// Open the csv file, and parse it ahead of time.
const file = await open('data.csv');
// The `csv.parse` function consumes the entire file at once, and returns
// the parsed records as a SharedArray object.
const csvRecords = await csv.parse(file, { delimiter: ',' })

export default async function() {
	// The csvRecords a SharedArray. Each element is a record from the CSV file, represented as an array
	// where each element is a field from the CSV record.
	//
	// Thus, `csvRecords[scenario.iterationInTest]` will give us the record for the current iteration.
	console.log(csvRecords[scenario.iterationInTest])
}
```

### Before this PR

CleanShot 2025-12-16 at 11 00 37

### After this PR

CleanShot 2025-12-16 at 10 58 23

## Checklist

- [X] I have performed a self-review of my code.
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have added tests for my changes.
- [X] I have run linter and tests locally (`make check`) and all pass.

## Checklist: Documentation (only for k6 maintainers and if relevant)

**Please do not merge this PR until the following items are filled out.**

- [X] I have added the correct milestone and labels to the PR.
- [ ] I have updated the release notes: _link_
- [ ] I have updated or added an issue to the [k6-documentation](https://github.com/grafana/k6-docs): grafana/k6-docs#NUMBER if applicable
- [X] I have updated or added an issue to the [TypeScript definitions](https://github.com/grafana/k6-DefinitelyTyped/tree/master/types/k6): grafana/k6-DefinitelyTyped#NUMBER if applicable

### CODE REVIEW

File: internal/js/modules/k6/data/data.go [hunk 1]
```diff
@@ -104,66 +109,106 @@ type RecordReader interface {
...
+		return slot
 	}
 
-	return array
+	slot = &sharedArraySlot{}
+	if s.slots == nil {
+		s.slots = make(map[string]*sharedArraySlot)
+	}
+	s.slots[name] = slot
+	return slot
```
Comment (joanlopez) [inline internal/js/modules/k6/data/data.go]:
```suggestion
	if s.slots == nil {
		s.slots = make(map[string]*sharedArraySlot)
	}
	slot = &sharedArraySlot{}
	s.slots[name] = slot
	return slot
```

Nit, absolutely non-blocking! As I generally prefer to have variables defined as close as possible to wherever are used.

File: internal/js/modules/k6/data/data.go [hunk 2]
```diff
@@ -104,66 +109,106 @@ type RecordReader interface {
...
+// This method is thread-safe. The callable is guaranteed to be invoked at most once
+// for each unique name, even if multiple goroutines call get concurrently with the
+// same name.
 func (s *sharedArrays) get(rt *sobek.Runtime, name string, call sobek.Callable) sharedArray {
+	slot := s.ensureSlot(name)
+	slot.once.Do(func() {
+		slot.arr = getShareArrayFromCall(rt, call)
+	})
+	return slot.arr
+}
```
Comment (joanlopez) [inline internal/js/modules/k6/data/data.go]: Although this may look a bit nitpicky, and it isn't a red flag that we should fix before merging, I think it's better, for the future ourselves, if we can merge `get` and the new `loadOrStore` introduced in this pull request, as they do essentially the same, and I can only think of bad consequences of having these two in the long term (e.g. bugs introduced because of the code duplication, etc).

Note that you can replace the existing call to `get`:

```go
array := d.shared.get(rt, name, fn)
``` 

with:

```go
builder := func() sharedArray { return getShareArrayFromCall(rt, fn) }
array := d.shared.loadOrStore(name, builder)
```

_(or even inlined, if that looks prettier to you)_

In other words; as you've already created `loadOrStore`, which is parameterized with a generic builder like: `builder func() sharedArray`, you can simply use different _builders_ depending on whether you're calling `loadOrStore` from the JS constructor or the Go constructor.

Regarding which one to leave, I have no strong preference between `get` or `loadOrStore`, but its form will need to be the one you used for `loadOrStore`.

File: internal/js/modules/k6/data/share_test.go [hunk 3]
```diff
@@ -251,3 +253,74 @@ func TestSharedArrayRaceInInitialization(t *testing.T) {
...
+	t.Parallel()
+
+	arrays := &sharedArrays{
+		slots: make(map[string]*sharedArraySlot),
+	}
+
+	var buildsCount atomic.Int32
+	builder := func() sharedArray {
+		buildsCount.Add(1)
+		time.Sleep(5 * time.Millisecond)
```
Comment (joanlopez) [inline internal/js/modules/k6/data/share_test.go]: Do we really need this `time.Sleep`? 🤔

**Review by joanlopez — DISMISSED** [review]
Great job @oleiade! 

Note that none of the comments I left are blocking, but I'd really appreciate if we can "merge" the two "duplicated" methods 🙏🏻

**Comment by inancgumus** [comment]
I've moved this to the 1.6.0 milestone, as we're in the release process.

File: internal/js/modules/k6/data/data.go (hunk 1 above)
Comment (oleiade) [reply internal/js/modules/k6/data/data.go]: Makes total sense 🙇🏻

File: internal/js/modules/k6/data/data.go (hunk 2 above)
Comment (oleiade) [reply internal/js/modules/k6/data/data.go]: That's a very good point! 👍🏻 

I'll keep `loadOrStore` then 🙇🏻

File: internal/js/modules/k6/data/share_test.go (hunk 3 above)
Comment (oleiade) [reply internal/js/modules/k6/data/share_test.go]: Indeed not, some debugging left behind, good catch! Removed ✅

**Comment by oleiade** [comment]
I've made a pass on the underlying SharedArray code as per your concerns @codebien and found that it's already pretty well tests. However, I've added a bunch of further tests to the data package, in order to limit the risks of breaking anything with our internal changes in this PR. Hope that's satisfying 🙇🏻

**Comment by oleiade** [comment]
Happy to split the PR.

However, most of the changes in the data module are dependencies for the CSV fix. The standalone parts (mostly increased test coverage in data_test.go and share_test.go to safeguard SharedArray) are isolated in my last commit.

I realize the `data` module is sensitive. But this was the best solution I could come up with at the time.

An alternative to the current approach I've been tinkering with might be to extract the 'shared memory' logic into a dedicated package that provides shared data structure used by `csv`, and that we could extend to further modules that might need that too in the future (`fs`), to tackle this need to initialize once, reuse multiple times that we tried to address here.. This would decouple it from the data module's specific implementation.

Plus, we could, if we so choose, migrate the data module to the new package down the road too. I think it could make sense, what do you folks think @codebien @joanlopez any other alternatives?

File: internal/js/modules/k6/data/data.go [hunk 4]
```diff
@@ -29,8 +29,13 @@ type (
...
 
 	sharedArrays struct {
-		data map[string]sharedArray
-		mu   sync.RWMutex
+		slots map[string]*sharedArraySlot
+		mu    sync.RWMutex
+	}
+
+	sharedArraySlot struct {
+		once sync.Once
```
Comment (mstoykov) [inline internal/js/modules/k6/data/data.go]: The once here seems to only exist so we call the `builder` once .... but we already have a protection in place to only make one sharedarray per each name - the mutex above.

So it seems more reasonable to just push the builder in ensureSlot as well and call it in there when created than anything else.

Comment (mstoykov) [reply internal/js/modules/k6/data/data.go]: This also removes the need for one more type and putting a pointer in the map

File: internal/js/modules/k6/data/data.go [hunk 5]
```diff
@@ -104,69 +110,95 @@ type RecordReader interface {
...
-	return array
+	s.mu.Lock()
+	defer s.mu.Unlock()
+	if slot, ok = s.slots[name]; ok {
+		return slot
+	}
+
+	if s.slots == nil {
+		s.slots = make(map[string]*sharedArraySlot)
+	}
```
Comment (mstoykov) [inline internal/js/modules/k6/data/data.go]:
```suggestion
```

File: internal/js/modules/k6/data/data.go (hunk 4 above)
Comment (oleiade) [reply internal/js/modules/k6/data/data.go]: Good idea, much appreciated, gonna look into it 👍🏻

**Comment by oleiade** [comment]
Hey folks 👋🏻 

Thanks a lot for the constructive feedback. I went back back to a less intrusive set of changes, leveraging the mutex as opposed to introduce a new `sync.Once`+slots based system.

I took the liberty to rewrite the history for clarity too, as I think it serves the review in this specific case.

Also removed the commit adding test coverage to `SharedArray`, and will open a separate PR 🙇🏻

File: internal/js/modules/k6/data/data.go [hunk 6]
```diff
@@ -104,69 +105,88 @@ type RecordReader interface {
...
+	// Double-check after acquiring write lock
+	if arr, ok = s.data[name]; ok {
+		return arr
 	}
 
-	return array
+	// Create and initialize the array
+	if s.data == nil {
+		s.data = make(map[string]sharedArray)
+	}
```
Comment (codebien) [inline internal/js/modules/k6/data/data.go]:
```suggestion
```
If a sharedArray exists then I expect it's already initialized. I don't see a concrete usage to use a non initialized SharedArray. This operation should happen in the constructor.

Considering the complex world where SharedArray operates I'd prefer as linear as possible logic.

Comment (mstoykov) [reply internal/js/modules/k6/data/data.go]: This actually already is set when the module is created

**Review by codebien — APPROVED** [review]
