### PR TITLE
fix: do not panic on `k6 login cloud`

### LINKED ISSUE #5055: `k6 login cloud` panicking with 1.2.1 upgrade
### Brief summary

With the upgrade to `1.2.1` from `1.1.0` we started seeing panics from using the deprecated `k6 login cloud` command as `k6 login` now only accepts `influxdb`.

It's not a huge deal as we can update our scripts that use `k6 login cloud` to the new `k6 cloud login` command, but flagging that this wasn't mentioned in the release notes if it was intended to be removed, or whether it should fail more gracefully rather than panicking.

```
$ k6 login
Command "login" is deprecated, and will be removed in a future release. Please use the "k6 cloud login" command instead.

Usage:
  k6 login [flags]
  k6 login [command]

Available Commands:
  influxdb    Authenticate with InfluxDB

Flags:
  -h, --help   help for login
```

### k6 version

1.2.1

### OS

macOS and Ubuntu

### Docker version and image (if applicable)

_No response_

### Steps to reproduce the problem

1. Run `k6 login cloud`

### Expected behaviour

Based on the release notes, the warning to appear when running the command but the login still working.

### Actual behaviour

```
$ k6 login cloud -t foo
Command "cloud" is deprecated, and will be removed in a future release.
Please use the "k6 cloud login" command instead.

ERRO[0000] unexpected k6 panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x64
go.k6.io/k6/internal/cmd.(*rootCommand).execute.func2()
	go.k6.io/k6/internal/cmd/root.go:135 +0x54
panic({0x103c62080?, 0x140001b44f8?})
	runtime/panic.go:792 +0x124
go.k6.io/k6/internal/cmd.analyze(0x1400025d8c8, {0x1400019f440, 0x0, 0x105143d48?})
	go.k6.io/k6/internal/cmd/launcher.go:305 +0x394
go.k6.io/k6/internal/cmd.(*launcher).launch(0x140002a6b70, 0x14000327348, {0x1400019f440, 0x0, 0x2})
	go.k6.io/k6/internal/cmd/launcher.go:88 +0x144
go.k6.io/k6/internal/cmd.(*rootCommand).persistentPreRunE(0x140001cdd40, 0x14000327348, {0x1400019f440, 0x0, 0x2})
	go.k6.io/k6/internal/cmd/root.go:118 +0xe4
github.com/spf13/cobra.(*Command).execute(0x14000327348, {0x1400019f420, 0x2, 0x2})
	github.com/spf13/cobra@v1.4.0/command.go:835 +0x4c4
github.com/spf13/cobra.(*Command).ExecuteC(0x14000319348)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x318
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.4.0/command.go:902
go.k6.io/k6/internal/cmd.(*rootCommand).execute(0x140001cdd40)
	go.k6.io/k6/internal/cmd/root.go:143 +0xc8
go.k6.io/k6/internal/cmd.ExecuteWithGlobalState(0x1400025d8c8)
	go.k6.io/k6/internal/cmd/root.go:35 +0xac
go.k6.io/k6/cmd.Execute()
	go.k6.io/k6/cmd/execute.go:16 +0x30
main.main()
	go.k6.io/k6/main.go:9 +0x1c
```

### PR DESCRIPTION
**Pull request by mstoykov**
## What?

This happened due to auto extension resolution wrongly guessing that `cloud` here means it needs to analyze a script. But it doesn't, and consequently panics.

## Why?
Panics are bad.
## Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests for my changes.
- [ ] I have run linter and tests locally (`make check`) and all pass.

## Checklist: Documentation (only for k6 maintainers and if relevant)

**Please do not merge this PR until the following items are filled out.**

- [ ] I have added the correct milestone and labels to the PR.
- [ ] I have updated the release notes: _link_
- [ ] I have updated or added an issue to the [k6-documentation](https://github.com/grafana/k6-docs): grafana/k6-docs#NUMBER if applicable
- [ ] I have updated or added an issue to the [TypeScript definitions](https://github.com/grafana/k6-DefinitelyTyped/tree/master/types/k6): grafana/k6-DefinitelyTyped#NUMBER if applicable

## Related PR(s)/Issue(s)
Fixes #5055

### CODE REVIEW

**Review by oleiade — APPROVED** [review]

**Comment by mstoykov** [comment]
After merging this I will be backporting this to v1.2.x and releasing 1.2.2

File: internal/cmd/launcher.go [hunk 1]
```diff
@@ -333,8 +333,21 @@ func analyze(gs *state.GlobalState, args []string) (k6deps.Dependencies, error)
...
+			}
+		}
+	case "upload":
+		if parent := cmd.Parent(); parent != nil {
+			return parent.Name() == "cloud"
+		}
+	case "cloud", "archive", "inspect":
+		if parent := cmd.Parent(); parent != nil {
+			return parent.Name() == "k6"
+		}
```
Comment (pablochacin) [inline internal/cmd/launcher.go:350]: I'm not sure what command mis-identification we are covering with the `run` and `upload`, `archive`, and `inspect` cases, as all those commands must have a script.

In other words, why a naive case for  `cloud`  that checks it is a `k6 cloud` (and not `k6 login cloud`) is not sufficient?

Comment (mstoykov) [reply internal/cmd/launcher.go:350]: I just decided that making this more explicit in all cases instead of just taking one of the cases out.

 Doing my original change I forgot about switches not being fallthrough in go (which is strange as I have mostly been writing go for 7+ years at this point).

Comment (pablochacin) [reply internal/cmd/launcher.go:350]: > I just decided that making this more explicit in all cases instead of just taking one of the cases out.

I find this confusing. It makes it harder to parse the intention of the validation. More so when the single case we are taking out is a deprecated command that will (I hope) be removed. I would find it more readable to make this comment and make this single check.

Comment (mstoykov) [reply internal/cmd/launcher.go:350]: I think part of the problem was that hte original code looked simple and that it did a thing - checkign what the bae command is, but it does actually checks the last sub command .

This code makes it painfully obvious that the original code isn't what it looks like. 

The deprecated command will be around for more than half a year and is still part of our contract wiht users for stability for the duration of 1.x.

So I would really prefer if we can merge and release .1 instead of discussing if we should have 1 or 2 lines that do the same thing. 

I also do intend on removing k6deps from k6 at this point because this kinds of problems are *exactly* what I was explaining when I was saying that what is being done is just wrapping k6 trying to make the same behaviour as the original k6.

Comment (pablochacin) [reply internal/cmd/launcher.go:350]: > So I would really prefer if we can merge and release .1 instead of discussing if we should have 1 or 2 lines that do the same thing.

I'm not blocking the merge, just sharing my perspective as a reviewer about the legibility of the code.
