### PR TITLE
fix for registering nested message types

### LINKED ISSUE #3160: grpc module is not registering protobuf nested messages
Hey folks!

I noticed that modules `k6/net/grpc` and `k6/experimental/grpc` are not registering the [nested types](https://protobuf.dev/programming-guides/proto3/#nested) defined in my `.proto` file. This means that when receiving the response (via stream) from the server, it is not possible to generate a javascript object via marshaling (and thus I am not able to proceed with the load test).

I've been debugging the code and saw that the fix could be made at this point (based on the module `k6/experimental/grpc`):
https://github.com/grafana/k6/blob/6137c5e2503389f8d205ea51ce269b71258cc842/vendor/github.com/grafana/xk6-grpc/grpc/client.go#L285-L295

Note that the above algorithm only goes through the _first level_ `messages` of the `.proto` file, but it is possible that a message has a list of _nested_ messages and so on recursively. It is possible to adjust the algorithm to traverse the data structure (tree) without the need to perform a recursion, although a recursion would be much simpler, since nobody defines so many nested levels.

Do you already have this fix mapped out to be resolved or can I propose a Pull Request?

### PR DESCRIPTION
**Pull request by thiagodpf**
## What?

`client.load()` (grpc module) was not registering protobuf nested messages in `protoregistry.GlobalTypes`.

## Why?

It was necessary to go through the message structures starting from the root, but as it was before the PR, it only registered the root message.

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have added tests for my changes.
- [x] I have run linter locally (`make ci-like-lint`) and all checks pass.
- [x] I have run tests locally (`make tests`) and all tests pass.
- [ ] I have commented on my code, particularly in hard-to-understand areas.

## Related PR(s)/Issue(s)

Closes #3160 issue.

backport from [xk6-grpc PR](https://github.com/grafana/xk6-grpc/pull/23)

### CODE REVIEW

**Review by mstoykov — DISMISSED** [review]

**Review by olegbespalov — APPROVED** [review]
Thanks again for your contribution! :rocket:

File: js/modules/k6/grpc/client_test.go [hunk 1]
```diff
@@ -977,3 +979,64 @@ func TestClientInvokeHeadersDeprecated(t *testing.T) {
...
+		samples chan metrics.SampleContainer
+	}
+	setup := func(t *testing.T) testState {
+		t.Helper()
+
+		tb := httpmultibin.NewHTTPMultiBin(t)
+		samples := make(chan metrics.SampleContainer, 1000)
+		testRuntime := modulestest.NewRuntime(t)
+
+		cwd, err := os.Getwd()
```
Comment (mstoykov) [inline js/modules/k6/grpc/client_test.go:998]:
```suggestion
		cwd, err := os.Getwd() //nolint:forbidigo
```

**Review by olegbespalov — APPROVED** [review]

**Review by mstoykov — APPROVED** [review]
