### PR TITLE
Enforce stack info for cloud commands

### LINKED ISSUE #5651: CLI Cloud commands: make stack info mandatory
### Feature Description

The new stack option added to the Cloud configuration in https://github.com/grafana/k6/pull/5420 should become as mandatory as the token information. If it's not provided, the command should fail. 

It can be specified in different ways:
- When running the `k6 cloud login` command with the `--stack` parameter or using the interactive mode (in this case, this should be the stack slug or full URL)
- In the script options, adding the `stackID` option
- In the env variables, using the `K6_CLOUD_STACK_ID` env variable

It would be nice to make the different options a bit more consistent and either use the stack slug everywhere, or support stack slug/url/id everywhere. 

### Suggested Solution (optional)

_No response_

### Already existing or connected issues / PRs (optional)

_No response_

### PR DESCRIPTION
**Pull request by codebien**
Closes #5651 

## What?

This PR makes Stack mandatory value for all cloud commands (`k6 cloud run`, `k6 cloud upload`, `k6 cloud run --local-execution`), completing the deprecation warning introduced in #5420.

## Note about differences from the original proposal

The original issue (#5650) proposed making stack input consistent across all input methods — accepting slug, full URL, or numeric ID interchangeably in all contexts. This PR does **not** fully unify the input formats: `K6_CLOUD_STACK_ID` and the `stackID` script option still accept a numeric ID only, while `k6 cloud login --stack` accepts a slug or full URL. Full input-format unification is left for a following dedicated work (probably after v2 release).

## Note about implementation details

- `k6 cloud login` now requires both token and stack — passing `-t` without `--stack` (or vice versa) fails with an explicit error. The previous behavior of accepting a token-only login and falling back to v1 token validation has been removed.
- Token masking in `--show` output: the stored token is now partially masked to avoid accidental credential exposure.
- Interactive login no longer offers `None` as a valid nor default stack option — both fields are required.
- Removed the v1 token-only validation path (`/v1/validate-token`). All authentication now goes through the v6 API (`/cloud/v6/auth`), which validates both token and stack together.

### CODE REVIEW

File: internal/cmd/cloud_login.go [hunk 1]
```diff
@@ -182,39 +152,96 @@ func (c *cmdCloudLogin) run(cmd *cobra.Command, _ []string) error {
...
+	const notSet = "<not set>"
+	token, stackID, stackURL, defProj := notSet, notSet, notSet, notSet
+
+	if cloudConf.Token.String != "" {
+		// If a token is set then we assume we have a valid token longer than 8 chars
+		// print the token with all the chars masked, except the first and the last four
+		unmasked := cloudConf.Token.String
+		asterisks := strings.Repeat("*", len(unmasked)-8)
+		token = unmasked[:4] + asterisks + unmasked[len(unmasked)-4:]
+	}
```
Comment (mstoykov) [inline internal/cmd/cloud_login.go:214]: I do not really want someone to get a panic because they copy-pasted the token wrongly nad it ended up being 4 character long. 

I guess the easiest solution here is to just ignore short tokens? 


```suggestion
	if cloudConf.Token.String != "" && len(cloudConf.Token.String) >= 8 {
		// If a token is set then we assume we have a valid token longer than 8 chars
		// print the token with all the chars masked, except the first and the last four
		unmasked := cloudConf.Token.String
		asterisks := strings.Repeat("*", len(unmasked)-8)
		token = unmasked[:4] + asterisks + unmasked[len(unmasked)-4:]
	}
```

**Review by mstoykov — DISMISSED** [review]
LGTM! 

On second pass through that it seems that the print only happens on show, so I guess it was already verified , so you can ignore it.

File: internal/cmd/cloud_login.go (hunk 1 above)
Comment (codebien) [reply internal/cmd/cloud_login.go:214]: @mstoykov I've thought about it, and I wanted to check if this can actually happen in practice. Btw, I'm not against avoid it, but just not sure that hiding them is the best UX. Shouldn't we just skip the masking and dump the token instead?

Comment (mstoykov) [reply internal/cmd/cloud_login.go:214]: oh you mean that we do not print the token at all in this case :facepalm: Okay yeah - I guess we should set token := cloudConf.Token.String before this block and then mask only if it is there and is over 8 characters. 


AGAIN - given that this can only really happen if this is in the config and we ... can not have a token that is udner 8 characters it doesn't matter all taht mcuh.

Alternative is to just either it be "empty" or "REDACTED" to signify that it is either there or not. I guess it will be useful to know the last and first few characters if you wonder if it is the wrong value ... but :shrug:

Comment (codebien) [reply internal/cmd/cloud_login.go:214]: https://github.com/grafana/k6/pull/5833/changes/78d3cfe9815bf9e94f09f637750479c12189fda8 it should be now generic

**Review by mstoykov — DISMISSED** [review]

**Review by mstoykov — APPROVED** [review]

File: internal/cmd/cloud.go [hunk 2]
```diff
@@ -31,10 +31,22 @@ import (
...
+// Together they represent a complete Grafana Cloud login.
+func checkCloudLogin(conf cloudapi.Config) error {
+	if !conf.Token.Valid || conf.Token.String == "" {
+		return errUserUnauthenticated
+	}
+	if !conf.StackID.Valid || conf.StackID.Int64 == 0 {
+		return errUserUnauthenticated
+	}
+	return nil
+}
```
Comment (inancgumus) [inline internal/cmd/cloud.go:49]: `checkCloudLogin()` collapses “missing token” and “missing stack” into the same `errUserUnauthenticated`, so users with only a token get only a generic authentication message. Would be nicer to return distinct errors, or at least include the specific missing piece in the message.

File: internal/cmd/cloud_login.go [hunk 3]
```diff
@@ -182,39 +152,108 @@ func (c *cmdCloudLogin) run(cmd *cobra.Command, _ []string) error {
...
+	// We try to have a good DX here.
+	// A valid Cloud token should be 12+ chars, so it prints the token with all
+	// the chars masked, except the first and the last four.
+	asterisks := strings.Repeat("*", len(unmasked)-8)
+	return unmasked[:4] + asterisks + unmasked[len(unmasked)-4:]
 }
 
-// validateInputs validates a token and a stack if provided
+// tokenAuthentication validates a token and a stack
```
Comment (inancgumus) [inline internal/cmd/cloud_login.go]: Tiny nit.
```suggestion
// authenticateUserToken validates a token and a stack
```

**Review by inancgumus — COMMENTED** [review]
Clean work 👍 Some nits only.

**Review by mstoykov — APPROVED** [review]

**Comment by codebien** [comment]
Hey @inancgumus, I've addressed your request changes in a specific pull request so we avoid to block the merge of this pull request. Please, take a look there https://github.com/grafana/k6/pull/5869.

Can you review the current pull request again, please?

**Review by inancgumus — APPROVED** [review]

File: internal/cmd/cloud.go (hunk 2 above)
Comment (inancgumus) [reply internal/cmd/cloud.go:49]: This is now handled by #5869.
