### PR TITLE
Don't error on adding submetrics again, reuse them

### LINKED ISSUE #2538: Thresholds on `http_req_duration{expected_response:true}` error on v0.38.x
### Brief summary

If you make a threshold on `http_req_duration{expected_response:true}` (or any other predefined metric with submetric, which currently is only this one) you will get back an error
```
ERRO[0000] sub-metric with params 'expected_response:true' already exists for metric http_req_duration: http_req_duration{expected_response:true}
```

originally reported on [the k6 slack](https://k6io.slack.com/archives/C3E688J8Z/p1652727820707979)

### k6 version

v0.38.0 to v0.38.2

### OS

all

### Docker version and image (if applicable)

_No response_

### Steps to reproduce the problem

run 
```javascript
export let options = {
  thresholds: {
    'http_req_duration{expected_response:true}': ['avg<400', 'p(95)<800', 'p(99)<2000']
  },
}
export default () => { }
```

### Expected behaviour

It works 

### Actual behaviour

You get 
```
ERRO[0000] sub-metric with params 'expected_response:true' already exists for metric http_req_duration: http_req_duration{expected_response:true}
```

### PR DESCRIPTION
**Pull request by mstoykov**
fixes #2538

### CODE REVIEW

File: metrics/metric.go [hunk 1]
```diff
@@ -103,10 +103,7 @@ func (m *Metric) AddSubmetric(keyValues string) (*Submetric, error) {
 
 	for _, sm := range m.Submetrics {
 		if sm.Tags.IsEqual(tags) {
-			return nil, fmt.Errorf(
-				"sub-metric with params '%s' already exists for metric %s: %s",
-				keyValues, m.Name, sm.Name,
-			)
+			return sm, nil
```
Comment (mstoykov) [inline metrics/metric.go:106]: @oleiade can you remember a particular reason you decided to error out on this instead of returning the already added one?

Comment (oleiade) [reply metrics/metric.go:106]: None 😞 Sorry for the annoyance! 🙇🏻

**Review by oleiade — APPROVED** [review]

**Review by olegbespalov — APPROVED** [review]
