### PR TITLE
fix: Implementing a limitation for the open()

### LINKED ISSUE #1771: open() seems to not always return the full data if that wasn't loaded in __VU =0
The following code:
```javascript
if (__VU >0) {
JSON.parse(open("./arr.json"));
}
```
Where arr.json is sufficiently big JSON seems to fail sometimes because not the whole JSON gets loaded. 

This is, technically, a  bad script, but maybe it should fail in another way that is more explanatory of what is happening or not at all

### PR DESCRIPTION
**Pull request by olegbespalov**
Implementing a limitation for the open() that limits opening files
by the list of the files that were opened during the initialization
step (__VU == 0).

For example, a code like:

```js
if (__VU >0) {
   JSON.parse(open("./arr.json"));
}
```

Should return an error.

Closes #1771

### CODE REVIEW

File: js/initcontext.go [hunk 1]
```diff
@@ -317,6 +313,40 @@ func (i *InitContext) Open(ctx context.Context, filename string, args ...string)
 	return i.runtime.ToValue(string(data)), nil
 }
 
+func readFile(fileSystem afero.Fs, filename string) ([]byte, error) {
+	// Workaround for https://github.com/spf13/afero/issues/201
+	if isDir, err := afero.IsDir(fileSystem, filename); err != nil {
```
Comment (MStoykov) [inline js/initcontext.go:318]: Because of this the following code:
```
if (__VU == 1) {
   open("./somenonexistingfile.js")
}
```

errors out with "no such file or directory" instead of the message below. This can be fixed later, as at least I don't know of a good fix without having to reimplement `fs.Stat` as well and we want to [move away](#1079 ) from afero either way. On the other hand that doesn't seem like that big of a change so :shrug:

**Review by MStoykov — CHANGES_REQUESTED** [review]
LGTM, nicely done :clap: ! 

I have left some nitpick comments, but mostly I want the message fixed ... possibly when the file is missing as well :). 
I have tested it and it seems to work great with archives as well ;)

File: js/initcontext.go (hunk 1 above)
Comment (olegbespalov) [reply js/initcontext.go:329]: That's fine. It's a tiny change :+1:

**Comment by olegbespalov** [comment]
Thanks, @MStoykov :bow: 

Addressed all comments :+1:

File: lib/fsext/cacheonread.go [hunk 2]
```diff
@@ -21,27 +21,95 @@
...
+	"errors"
+	"os"
+	"sync"
 	"time"
 
 	"github.com/spf13/afero"
 )
 
+// ErrPathNeverRequestedBefore represent an error when path never opened/requested before
+var ErrPathNeverRequestedBefore = errors.New("path nevere requested before")
```
Comment (MStoykov) [inline lib/fsext/cacheonread.go:33]:
```suggestion
var ErrPathNeverRequestedBefore = errors.New("path never requested before")
```

File: js/initcontext.go [hunk 3]
```diff
@@ -317,6 +313,40 @@ func (i *InitContext) Open(ctx context.Context, filename string, args ...string)
...
+	defer func() {
+		if errors.Is(err, fsext.ErrPathNeverRequestedBefore) {
+			// loading different files per VU is not supported, so all files should are going
+			// to be used inside the scenario should be opened during the init step (without any conditions)
+			err = fmt.Errorf(
+				"open() can't be used under with files that weren't opened during initialization (__VU==0), path: %q",
+				filename,
+			)
+		}
+	}()
```
Comment (MStoykov) [inline js/initcontext.go:326]: Note(not actionable): Technically, this error will either happen on `afero.IsDir` or not at all. But it seems kind of strange to check it only there and also when/if we ever stop checking that as we move to [io/fs](#1079) it will be a bit confusing why it wasn't previously checked.

I am noting this for future reference only, don't do anything about it just based on that.

File: js/initcontext.go [hunk 4]
```diff
@@ -317,6 +313,40 @@ func (i *InitContext) Open(ctx context.Context, filename string, args ...string)
...
+func (i *InitContext) allowOnlyOpenedFiles() {
+	fs := i.filesystems["file"]
+
+	alreadyOpenedFS, ok := fs.(fsext.OnlyOpenedEnabler)
+	if !ok {
+		return
+	}
+
+	alreadyOpenedFS.AllowOnlyOpened()
+}
```
Comment (MStoykov) [inline js/initcontext.go:348]: Note(not actionable): This seems a bit fragile, as we can at any point  change what the top fs for `file` is and then this suddenly won't work. This is *unlikely* as this code is very rarely changed and will probably be spotted.

The test below also doesn't test with `loader.CreateFilesystems` which is what is used in reality. An integration test with it might be better, but I see no test actually has ever used it so :shrug: maybe there are some problems I can't remember at the moment. Either way this is fine for now, hopefully we will be moving to io/fs soon and that will lead to some bigger changes and hopefully more tests.

**Review by MStoykov — APPROVED** [review]
LGTM :clap: I have 2 more comments with notes, but I wouldn't argue you should work on them now especially if the plan is to move to io/fs in the next release, which will in practice redo all of this either way.

**Review by yorugac — CHANGES_REQUESTED** [review]
LGTM overall :+1: but I have a renaming request and some smaller cleanup remarks.

One more thing. To improve test coverage it might also make sense to add tests for successful cases (i.e. with `if (__VU==0)` and with absent `if` condition)?

File: js/runner_test.go [hunk 5]
```diff
@@ -1157,6 +1158,55 @@ func TestVUIntegrationOpenFunctionErrorWhenSneaky(t *testing.T) {
...
+func TestVUDoesNotOpenUnderConditions(t *testing.T) {
+	t.Parallel()
+
+	baseFS := afero.NewMemMapFs()
+	data := `
+			if (__VU > 0) {
+				data = open("/home/somebody/test.json");
+			}
+			exports.default = function(data) {
+				console.log("hey")
```
[the remark this answers is not in the document]
Comment (MStoykov) [reply js/runner_test.go:1170]:
```suggestion
			if (__VU > 0) {
				var data = open("/home/somebody/test.json");
			}
			exports.default = function() {
				console.log("hey")
```

File: js/runner_test.go [hunk 6]
```diff
@@ -1157,6 +1158,55 @@ func TestVUIntegrationOpenFunctionErrorWhenSneaky(t *testing.T) {
...
+func TestVUDoesNonExistingPathnUnderConditions(t *testing.T) {
+	t.Parallel()
+
+	baseFS := afero.NewMemMapFs()
+	data := `
+			if (__VU == 1) {
+				data = open("/home/nobody");
+			}
+			exports.default = function(data) {
+				console.log("hey")
```
Comment (MStoykov) [inline js/runner_test.go:1195]:
```suggestion
				let data = open("/home/nobody");
			}
			exports.default = function() {
				console.log("hey")
```

File: js/runner_test.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (yorugac) [reply js/runner_test.go:1170]: Yes, that's what I meant.

File: js/initcontext.go (hunk 3 above)
Comment (olegbespalov) [reply js/initcontext.go:326]: :thinking: not sure if I get it. The error happens `afero.IsDir` and `afero.ReadFile`. Even if we move to the `io/fs` still should happen on the equivalent of the `afero.ReadFile`, no?

Comment (MStoykov) [reply js/initcontext.go]: When we move – yes, but when we move to io/fs,  `afero.IsDir` will *hopefully* be just dropped ;). 

What I am trying to say is that if `afero.IsDir` did not return `fsext.ErrPathNeverRequestedBefore` than `afero.Readfile` will not return it either ... or we have bugs I guess or some strange race condition.

I wondered for a bit if we can't just add `afero.IsDir` check in the already reimplemented `Open` , but I am not certain we always use the CacheOnReadFs and IIRC we don't so :shrug:

**Review by MStoykov — APPROVED** [review]

**Review by yorugac — DISMISSED** [review]
Thanks for the renaming! LGTM :+1:

**Review by MStoykov — APPROVED** [review]

**Review by yorugac — APPROVED** [review]

File: js/bundle.go [hunk 7]
```diff
@@ -334,6 +334,10 @@ func (b *Bundle) instantiate(logger logrus.FieldLogger, rt *goja.Runtime, init *
 	unbindInit()
 	*init.ctxPtr = nil
 
+	if vuID == 0 {
+		init.allowOnlyOpenedFiles()
+	}
```
Comment (na--) [inline js/bundle.go:339]: I am probably be missing something, but this seems wrong? :confused: Isn't the whole point that VUs > 0 shouldn't be able to open non-cached files?

Comment (olegbespalov) [reply js/bundle.go:339]: Yes, the point is that VUs > 0 shouldn't be able to open non-cached files.

This line notifies the FS that VU#0 did the first run, and the list of "known" files list can be frozen.
