### PR TITLE
Limit the size of the warning from metrics' `Add()` methods

### LINKED ISSUE #2217: [Bug]: WARN messages can print megabytes of text
### k6 version

master

### OS

Linux

### Docker version and image

_No response_

### Expected Behaviour

WARN messages produced by https://github.com/grafana/k6/pull/1876 should trim the values.

### Actual Behaviour

WARN messages can be megabytes long. 
image

### Steps to Reproduce the Problem

```
import http from 'k6/http';
import { Counter } from 'k6/metrics';

let my_counter = Counter("my_counter");

export default function () {
  my_counter.add(http.get('https://test.k6.io').body)
}

```

### PR DESCRIPTION
**Pull request by MStoykov**
fixes #2217

### CODE REVIEW

File: js/modules/k6/metrics/metrics.go [hunk 1]
```diff
@@ -75,6 +77,21 @@ func (mi *ModuleInstance) newMetric(call goja.ConstructorCall, t stats.MetricTyp
 	return v.ToObject(rt), nil
 }
 
+const warnMessageValueMaxSize = 100
+
+func limitValue(v string) string {
+	if len([]rune(v)) < warnMessageValueMaxSize {
+		return v
+	}
+	vRunes := []rune(v)
```
Comment (na--) [inline js/modules/k6/metrics/metrics.go:86]: you can move this to the top of the function and then check `len(vRunes)` to avoid converting it twice

**Review by na-- — COMMENTED** [review]
LGTM in general, besides the minor nitpick, but can you please also add a test?

File: js/modules/k6/metrics/metrics.go (hunk 1 above)
Comment (MStoykov) [reply js/modules/k6/metrics/metrics.go:86]: I was thinking that `len([]rune(v))` might skip the making of the slice ... but looking at this again I kind of doubt it :facepalm: so I am gonna do it.

**Review by na-- — APPROVED** [review]

**Review by codebien — APPROVED** [review]
